before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
language: android
jdk:
- openjdk8
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-29.0.1
  - build-tools-28.0.3
  - android-29
  - extra-android-m2repository
  - extra-android-support
  - doc-29
branches:
  only:
  - master
script: "./travis-build.sh"
